import './globals.css'
import Footer from '@/components/footer/Footer'
import Navbar from '@/components/navigation/Navbar';
import "@fortawesome/fontawesome-svg-core/styles.css"; 
import { CartContextProvider } from './context/cartStore';
import { Toaster } from 'react-hot-toast';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body id='body'>
        <CartContextProvider>
          <nav>
              <Navbar />
          </nav>
            {children}
          <footer>
              <Footer />
          </footer>
          <Toaster position='bottom-right' toastOptions={{style: {margin: '4rem'}}} />
        </CartContextProvider>
      </body>
    </html>
  )
}
