import './globals.css'
import Footer from '@/components/footer/Footer'
import Navbar from '@/components/navigation/Navbar';
import "@fortawesome/fontawesome-svg-core/styles.css"; 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
            <Navbar />
        </nav>
          {children}
          <Footer />
      </body>
    </html>
  )
}
